### ISSUE TITLE
About README

### ISSUE THREAD

**Issue by Kotolegokot** [vahriin/Synopsises#3]
vk.com/i_m_root 

> Page Not Found

**Comment by vahriin** [comment]
Да, действительно, я сменил адрес. Извините за неудобства.
Новый: vk.com/vahriin
Обновленный README запушу в пятницу.

**Comment by Kotolegokot** [comment]
> Извините за неудобства.

Да лан, че ты :D

**Comment by vahriin** [comment]
> Да лан, че ты :D

**Comment by vahriin** [comment]
Исправлено
